### PR TITLE
fix(lookup): add class for validation renderer

### PR DESCRIPTION
**Pull request by MaximBalaganskiy**

### CODE REVIEW

**Comment by bigopon** [comment]
is there any reason the validation couldn't use `ux-lookup`? If we do this, we need to do it for every component.

**Comment by MaximBalaganskiy** [comment]
The renderer in the demo app relies on these classes. E.g. ux-input already has it

**Comment by ben-girardet** [comment]
I think we already do this for the other components. Plus I think it's very good to use BEM styles which requires us to declare the `.ux-lookup` class in the element.

**Comment by bigopon** [comment]
Cool, thanks for confirming @MaximBalaganskiy @ben-girardet lets go

**Pull request merged**
