### PR TITLE
feat(ux-card): add ux-card component

### PR DESCRIPTION
**Pull request by ZHollingshead**
Adds the UX Card component. The ux card has been made to work with the grid component and can be used directly in place of a `ux-grid-cell`.

**Usage**
```html
<ux-grid>
      <ux-card dense class="accent-header" md="6" lg="4">
        <header>
          <div class="title">
            Accent Header
            <div class="sub-title">dense</div>
          </div>
          <h2>800 Items</h2>
        </header>
        <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        </div>
      </ux-card>

      <ux-card dense class="primary-header" md="6" lg="4">
        <header>
          <div class="header-row">
            <div class="title">
              Primary Header Row
            </div>
            <div class="spacer"></div>
            <ux-button type="icon">
              <i class="material-icons">more_vert</i>
            </ux-button>
          </div>
          <h2>800 Items</h2>
        </header>
        <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        </div>
      </ux-card>

      <ux-card md="6" lg="4">
        <img src="https://zambullida.files.wordpress.com/2010/10/fotos-rosas-azules.jpg">
        <header>
          <div class="title">
            Image Card
          </div>
        </header>
        <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.
        </div>
      </ux-card>

      <ux-card dense md="6" lg="4">
        <img src="https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
        <header>
          <div class="title">
            Image Card
            <div div class="sub-title">Subtitle</div>
          </div>
        </header>
        <div class="card-content">
          Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris.
        </div>
        <footer>
          <ux-button type="flat">Flat UX-Button</ux-button>
          <a class="footer-action">Anchor Action</a>
        </footer>
      </ux-card>

      <ux-card dense md="6" lg="4">
        <img src="https://wallpaperbrowse.com/media/images/cat-1285634_960_720.png">
        <header>
          <div class="title">
            Image Card
          </div>
        </header>
        <div class="action-row">

          <ux-button type="icon">
            <i class="material-icons">share</i>
          </ux-button>
          <ux-button type="icon">
            <i class="material-icons">star</i>
          </ux-button>
          <ux-button type="icon">
            <i class="material-icons">more_vert</i>
          </ux-button>
          <div class="spacer"></div>
          <ux-button type="icon">
            <i class="material-icons">settings</i>
          </ux-button>
        </div>
        <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.
        </div>
        <footer>
          <ux-button type="flat">Flat UX-Button</ux-button>
          <a class="footer-action">Anchor Action</a>
        </footer>
      </ux-card>
</ux-grid>
```

**Visual Examples**
image
image

*Themed*
image
image

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Woohoo!!! Will review over the next couple of days. Very excited about this one :)

**Comment by EisenbergEffect** [comment]
@scriswell You might want to take a look as well :)

**Comment by scriswell** [comment]
Very Nice! Are we worried about BEM CSS styles or are we using something like CSS Modules for CSS scoping?

**Comment by ZHollingshead** [comment]
So far not using CSS Modules for the main reason that it leaves the components flexible, if the developer wants to change the styles bad enough they can do so without having to using anything more than basic CSS, though I try to make sure the selectors are specific enough that accidentally overriding styles should not be an issue.

Though the theming shown in those images above was accomplished by changing two of the CSS Variables at the root of the document that should apply across all components.

I will see if I can get a live version up and running in the showcase soon.

**Comment by scriswell** [comment]
I'm mostly concerned with generic class names like `class="title"`, `class="spacer"`, and `class="sub-title"`. Each of those could easily be used by mistake in other areas of an app and potentially cause some styling conflicts.

**Comment by scriswell** [comment]
Looking at `md="6" lg="4"`, these custom properties appear to work similarly to Bootstrap. Is there a semantic way to do this as well? In Bootstrap, for example, I could extend a class with the related CSS class for breakpoints using either SCSS or PostCSS. Do we have classes that handle this layout task as well? Out of curiosity why have we built custom properties for these as opposed to building a CSS class library for them?

**Comment by ZHollingshead** [comment]
I see what you are saying. Yes those are rather generic. Would you suggest something like `ux-card-title`?

So the grid we have implemented is very similar to bootstrap, though there is less setup. It works on top of the CSS Grid layout. The main reason it is not in its own CSS Class Library is because the `ux-grid` component will have to be there regardless as it offers certain functionality, such as being able to change the number of columns in the grid. `<ux-grid columns="15">` for example.

**Comment by scriswell** [comment]
This is better but something like `ux-card__title` would more closely align with BEM style expectations. With this solution, it's readily understandable that `ux-card__title` is an _element_ belonging to the `ux-card` component.

**Comment by scriswell** [comment]
I'd love to learn more about our `<ux-grid>` implementation but I won't bog down this pull request with that. ;)

This is really exciting stuff!

**Comment by ZHollingshead** [comment]
As a class name or an element name? I have never actually seen any elements named like that.

I have mixed feelings on it, but those are more due to personal style rather than any real reasons based in logic, so I can not really argue against it.

**Comment by scriswell** [comment]
Class name, sorry for the confusion. BEM refers to a child node of a parent component as an element.

**Comment by scriswell** [comment]
Here's a quick overview: https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

**Comment by ZHollingshead** [comment]
I may not enjoy how it looks, though the reasons behind it are sound. I do not mind updating the styles to look like this, particularly since the alternatives with CSS Modules while nice, limits what the developer can do in the end.

Here is a demo of the components live: https://aux-demo.firebaseapp.com/cards

I will start making those changes. (you can toggle the theme on that page in the upper right hand corner)

**Comment by khuongduybui** [comment]
Card subtitles are very hard to read in dark theme.

**Comment by scriswell** [comment]
@ZHollingshead I agree BEM is not syntactically elegant but it does add clarity, especially to large application codebases.

**Comment by scriswell** [comment]
@ZHollingshead I like the idea of having it be expressed as an element `<ux-card-content>`. It has more semantic meaning that the div and you can always add a custom class to the element to update the styles. @EisenbergEffect What do you think?

**Comment by ZHollingshead** [comment]
Would we also want to favor a `ux-card-header` and `ux-card-footer` element in place of a standard header and footer element? Thinking on it those elements are probably styled heavily in almost every application.

```html
<ux-card dense md="6" lg="4">
  <header>
    <div class="ux-card__title ux-card__title--small">
      Title
      <div div class="ux-card__sub-title">Subtitle</div>
    </div>
  </header>
  <div class="ux-card__action-row">
  </div>
  <div class="ux-card__card-content">
    Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris.
  </div>
  <footer>
    <ux-button type="flat">action</ux-button>
  </footer>
</ux-card>
```

vs


```html
<ux-card dense md="6" lg="4">
  <ux-card-header>
    <ux-card-card-title size="small">
      Title
      <small>Subtitle</small>
    </ux-card-card-title>
  </ux-card-header>
  <ux-card-action-row>
    <!-- actions here -->
  </ux-card-action-row>
  <ux-card-card-content>
    Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris.
  </ux-card-card-content>
  <ux-card-footer>
    <ux-button type="flat">action</ux-button>
  </ux-card-footer>
</ux-card>
```

**Comment by scriswell** [comment]
@ZHollingshead I like this approach but I would want to get @EisenbergEffect to share his thoughts as well. My thoughts are that custom Aurelia UX components should have their own elements but that they should easily map to standard markup when available. So what you've suggested above matches those thoughts.

**Comment by EisenbergEffect** [comment]
I'm good with adding more elements for semantic reasons, especially if it makes it easier to style. Let's just make sure we have aria attributes on everything.

**Comment by ZHollingshead** [comment]
I went ahead and updated the CSS.

Any custom elements aside from the ux-card element are currently defined only in the CSS, as I could not think of any aria attributes to apply to them.

The usage currently looks like this:

```html
    <ux-card md="6" lg="4">
      <ux-card-header>
        <ux-card-title size="small">
          Title
          <ux-card-sub-title>Dense</ux-card-sub-title>
        </ux-card-title>
      </ux-card-header>
      <ux-card-action-row>
        <ux-button type="icon">
          <ux-icon icon="share"></ux-icon>
        </ux-button>
        <ux-button type="icon">
          <ux-icon icon="bookmark"></ux-icon>
        </ux-button>
        <ux-button type="icon">
          <ux-icon icon="star"></ux-icon>
        </ux-button>
      </ux-card-action-row>
      <ux-card-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Integer nec odio. Praesent libero. Sed cursus ante dapibus
        diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
        Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed
        augue semper porta. Mauris massa. Vestibulum lacinia arcu
        eget nulla. Class aptent taciti sociosqu ad litora torquent per 
        conubia nostra, per inceptos himenaeos.
      </ux-card-content>
    </ux-card>

    <ux-card md="6" lg="4">
      <ux-card-header>
        <ux-card-header-row>
          <ux-card-title>
            Actions
          </ux-card-title>
          <ux-card-spacer></ux-card-spacer>
          <ux-button type="icon">
            <ux-icon icon="more_vert"></ux-icon>
          </ux-button>
        </ux-card-header-row>
      </ux-card-header>
      <ux-card-content>
        <ux-form>
          <ux-field label="First Name">
            <ux-input maxlength="10" value.bind="firstName"></ux-input>
            <ux-input-info ux-input-counter>John</ux-input-info>
          </ux-field>

          <ux-field label="Last Name">
            <ux-input maxlength="10" value.bind="lastName"></ux-input>
            <ux-input-info ux-input-counter>Doe</ux-input-info>
          </ux-field>
        </ux-form>
      </ux-card-content>
      <ux-card-footer>
        <ux-button type="flat">Flat UX-Button</ux-button>
        <a class="ux-card__action">Anchor Action</a>
      </ux-card-footer>
    </ux-card>

    <ux-card class="ux-card--primary-header" md="6" lg="4">
      <ux-card-header>
        <ux-card-title>
          Primary Header
          <ux-card-sub-title>standard</ux-card-sub-title>
        </ux-card-title>
        <h2>800 Items</h2>
      </ux-card-header>
      <ux-card-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Integer nec odio. Praesent libero. Sed cursus ante dapibus 
        diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. 
        Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue 
        semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. 
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, 
        per inceptos himenaeos.
      </ux-card-content>
    </ux-card>

    <ux-card dense class="ux-card--accent-header" md="6" lg="4">
      <ux-card-header>
        <ux-card-title size="small">
          Accent Header
          <ux-card-sub-title>dense</ux-card-sub-title>
        </ux-card-title>
        <h2>800 Items</h2>
      </ux-card-header>
      <ux-card-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.
        Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis 
        sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue 
        semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. 
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, 
        per inceptos himenaeos.
      </ux-card-content>
    </ux-card>
```

**Comment by dudluk** [comment]
This is looking great! I really like the version with custom elements.

What do you think about:

```html
<ux-card dense class="ux-card--primary-header">
  <ux-card-header>
  </ux-card-header>
  <ux-card-content>
  </ux-card-content>
</ux-card>
```
vs
```html
<ux-card dense>
  <ux-card-header color="primary">
  </ux-card-header>
  <ux-card-content>
  </ux-card-content>
</ux-card>
```

Maybe it would be good to support both options?

**Comment by dudluk** [comment]
I would nicely align with how other components are configured, for example:

```html
<ux-button type="flat" size="medium">

</ux-button>
```
But maybe it could be changed to:
```html
<ux-button class="ux-button--flat ux-button--medium">

</ux-button>
```

I prefer 1st option because is more compact and easier to read, but I think i's just personal preference. However it would be great to have consistent api across all components. 

Also, in the background _BEM-style_ classes can be generated. I'm talking only about component configuration api, not the internal css.

**Comment by ZHollingshead** [comment]
> Also, in the background BEM-style classes can be generated. I'm talking only about component configuration api, not the internal css.

I am against this purely because then you are setting up certain custom elements in Aurelia for the soul purpose of adding a CSS class, when CSS offers a way to handle that. I do not mind the styles being contained in selectors that include attributes because to me that makes sense.

I find attributes in CSS preferable even just due to the fact that if we are using BEM-style classes to reduce the chances of collisions, attributes will be the most specific we can get. We would not have to worry about global styles in that case.

**Comment by dudluk** [comment]
> I am against this purely because then you are setting up certain custom elements in Aurelia for the soul purpose of adding a CSS class, when CSS offers a way to handle that. I do not mind the styles being contained in selectors that include attributes because to me that makes sense.

I agree - it would be a big overhead. It could be handled by top level component - in this case `ux-card`, but it might by unnecessary either. I don't mind attribute based selectors. I'm not concerned about the implementation. 

The point I'm trying to make is as a developer I would prefer to have consistent way of configuring ux component. It can be either via attributes or css classes - personally I think attributes are a bit cleaner. Having a mix is be a bit confusing for me. 

For example:
```html
<ux-button class="accent" type="flat" effect="none" size="small" />
```
could be
```html
<ux-button color="accent" type="flat" effect="none" size="small" />
```
but I'm still fine with the original, it's just second version seems to be more consistent.

However:
```html
<ux-button class="ux-button--accent"  type="flat" effect="none" size="small" />
```
feels to be a bit harder to use for me.

But maybe it's not the best place to discuss it :)

**Comment by ZHollingshead** [comment]
This is ready for another pass.

**Pull request merged**
