### PR TITLE
Style engine update

### PR DESCRIPTION
**Pull request by ZHollingshead**
Updates to the style engine that allow UX Design Styles to be set through `applyTheme` and `applyThemeGroup`.

Enables the following:
```json
{
  "light": [
    {
      "themeKey": "design",
    
      "controlBackground": "#fff",
      "controlForeground": "#212121",
      "appBackground": "#fafafa",
      "appForeground": "#212121"
    }, {
    "themeKey": "toolbar",

    "shadow": "none",
    "background": "transparent",
    "foreground": "#333"
  }],
  "dark": [
    {
      "themeKey": "design",
    
      "controlBackground": "#373740",
      "controlForeground": "#fff",
      "appBackground": "#33333d",
      "appForeground": "#fff"
    }, {
    "themeKey": "toolbar",

    "shadow": "none",
    "background": "transparent",
    "foreground": "inherit"
  }]
}
```

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@ZHollingshead This looks great! Thanks for adding this feature. Is this ready to merge?

**Comment by ZHollingshead** [comment]
It is yes.

**Comment by EisenbergEffect** [comment]
Should we schedule another release? Also, I'm working on the quarterly update. I'll include this new feature as part of that. Do you have any thoughts on what you want to work on during the next quarter? Do you have availability to move forward with new things?

**Comment by ZHollingshead** [comment]
A minor release would be good.

I have a few thoughts. The biggest thing I want to look at and tackle is getting the CSS consistent across all the components. Additionally, I am examining some of the bullet points already laid out to see if there are any I have time to tackle at the moment.

**Comment by EisenbergEffect** [comment]
I'll put out a minor release with the new APIs. Thanks for working on this! This is a very nice new feature.

**Pull request merged**
