### PR TITLE
fix(components): components registration

### LINKED ISSUE #233: Error: Unable to find module with ID: @aurelia-ux/components/ux-button
**I'm submitting a bug report**
similar to #120 

* **Library Version:**
0.17.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v12.14.1

* **NPM Version:**
6.13.6

* **Webpack**
webpack-cli 3.3.10

* **Browser:**
Crome Version 79.0.3945.117 (Official Build) (64-bit)

* **Language:**
ESNext

**Current behavior:**
Registering plug-in `@aurelia-ux/components` in `main.js`
```
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature(PLATFORM.moduleName('resources/index'));

  aurelia.use
    .plugin(PLATFORM.moduleName('@aurelia-ux/core'))
    .plugin(PLATFORM.moduleName('@aurelia-ux/components'))
    .plugin(PLATFORM.moduleName('@aurelia-ux/icons'))
...
```

throws error
```
VM3058 eG:250 Possible Unhandled Promise Rejection: Error: Unable to find module with ID: @aurelia-ux/components/ux-button
    at WebpackLoader.eval (aurelia-loader-webpack.js?e63c:197)
    at step (aurelia-loader-webpack.js?e63c:41)
    at Object.eval [as next] (aurelia-loader-webpack.js?e63c:22)
    at eval (aurelia-loader-webpack.js?e63c:16)
    at doResolve (VM3058 eG:135)
    at new Promise (VM3058 eG:39)
    at __awaiter (aurelia-loader-webpack.js?e63c:12)
    at WebpackLoader._import (aurelia-loader-webpack.js?e63c:162)
    at WebpackLoader.eval (aurelia-loader-webpack.js?e63c:262)
    at step (aurelia-loader-webpack.js?e63c:41)
    at Object.eval [as next] (aurelia-loader-webpack.js?e63c:22)
    at eval (aurelia-loader-webpack.js?e63c:16)
    at doResolve (VM3058 eG:135)
    at new Promise (VM3058 eG:39)
    at __awaiter (aurelia-loader-webpack.js?e63c:12)
    at WebpackLoader.loadModule (aurelia-loader-webpack.js?e63c:249)
    at eval (aurelia-loader-webpack.js?e63c:240)
    at Array.map (<anonymous>)
    at WebpackLoader.loadAllModules (aurelia-loader-webpack.js?e63c:240)
    at ViewEngine.importViewResources (VM3108 hij8:3629)
    at eval (aurelia-framework.js?0682:231)
    at eval (VM3058 eG:59)
```

**Expected/desired behavior:**

* **What is the expected behavior?**
All components defined in `aurelia-ux` are registered and ready to use without any additional registration.

* **Workaround**
Register all components manually like [here](https://github.com/aurelia/ux/blob/master/app/src/main.ts)

### PR DESCRIPTION
**Pull request by ben-girardet**
Fixes #233 

I've included another fix, [exposing all (*) variables from components](https://github.com/aurelia/ux/commit/50e70ee0b0c054e8189fe44c903651cc8931f711). I don't see a reason why we would not expose all the variables exposed from the components themselves. But maybe I missed something. Let me know.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @ben-girardet !

@serifine Can you think of a reason why we might not have handled it this way before? Were there items we explicitly did not want to expose as part of the public API?

@bigopon Any thoughts?

**Comment by bigopon** [comment]
I'm neutral on this. pros&cons:
pros:
- centralized place to get all exports, comfortable, easy to teach
cons:
- some extra B for the code generated for non-esm module

Though I think the cons is minimal, as we don't have a lot of exports in our components. And we actually may need to fix this, as all internal resources probably should be import-able from module index file (of other components).

So I think this PR is fine for the extra, and good for the fix.

**Comment by ben-girardet** [comment]
> Though I think the cons is minimal, as we don't have a lot of exports in our components. And we actually may need to fix this, as all internal resources probably should be import-able from module index file (of other components).

From my experience the most important thing is that, as you said, all internals should be import-able from each component index. At least each VM, each Theme and anything that can help users to extend parts of the library in their own projects.

@bigopon you say that re-exporting from the `component` package increases the size of the package. To what degree ?

For me I'm happy if we decide to re-export everything or nothing - either way. If we go for "nothing" we can even remove the previous exports that we previously had.

**Comment by EisenbergEffect** [comment]
I'm happy to merge this. Can we have a final confirmation from @ben-girardet and @bigopon ?

**Comment by bigopon** [comment]
Yes, lgtm

**Comment by EisenbergEffect** [comment]
Ok, merging and will get this out in the next couple of days.

**Comment by bigopon** [comment]
>  you say that re-exporting from the component package increases the size of the package. To what degree ?

I was just trying to crank out some cons so it doesn't look funny. We have limited number of exports so it should be fine

**Pull request merged**
