### PR TITLE
Control style updates

### PR DESCRIPTION
**Pull request by ZHollingshead**
Contains a conversion to BEM styles for CSS and style updates. 
Also contains various bug fixes both for CSS and Code.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @ZHollingshead !
@scriswell This PR has conversion to BEM styles as you originally requested along with other CSS fixes. Do you have any time to review it?

**Comment by ZHollingshead** [comment]
Any updates on this?

**Comment by EisenbergEffect** [comment]
@scriswell Have you had any chance to review this?

**Comment by scriswell** [comment]
I was at a conference over the weekend, and haven't had time to review yet.

**Comment by EisenbergEffect** [comment]
@ZHollingshead I think this is good but I wanted to get a sense for whether or not @scriswell would have time to review it or not before merging it in.

**Comment by ZHollingshead** [comment]
Just checking on this pull request.

**Comment by EisenbergEffect** [comment]
I guess @scriswell isn't available to review. I took a look previously and it looks good to me. @ZHollingshead you are the lead on this library and I trust your judgement :) Merging...

**Comment by EisenbergEffect** [comment]
@ZHollingshead Should I go ahead and release this tonight?

**Comment by ZHollingshead** [comment]
Yes, a release tonight would be good.

**Pull request merged**
