### PR TITLE
refactor(all): update build

### PR DESCRIPTION
**Pull request by bigopon**
This PR should make it easier overall to contribute, build & test changes in UX components.

Summary of changes:
- use rollup for build, and distribute a single script file with sourcemap instead of using tsc
- distribute typings in `dist/types` folder
- distribute css remain the same
- all views of UX elements are import and inlined via `@inlineView`
- ensure each package export everything in `index.ts`
- use static resources convention for ux components in each package `configure` function
- update (dev)dependencies to latest
- create a test app, aliasing ux packages to the source code for better testing experience
- add ability to built to a specific folder, like following example (included in readme):
```shell
npm run build -- --environment target_dir: path/to/my/dir
# or
npm run build:dev -- --environment target_dir: path/to/my/dir
# or
npm run build:dev:watch -- --environment target_dir: path/to/my/dir
```
- fix minor issues in some components

@EisenbergEffect @serifine

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bigopon I've got the DI release out. Do we need to make any more changes to this PR now or do I just merge and release?

**Comment by bigopon** [comment]
Only need to merge, build and release.

**Comment by bigopon** [comment]
@EisenbergEffect when building locally, maybe upgrade DI to new version too, since lock file could prevent that automatic uipdate

**Comment by ben-girardet** [comment]
@bigopon works like a charm. Thank you!!

**Pull request merged**
