### PR TITLE
Fix #30

### LINKED ISSUE #30: Build fails
**I'm submitting a bug report**

* **Library Version:**
aurelia-ux 0.1.14

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.5

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
N/A

* **Language:**
TypeScript 2.1.4 

**Current behavior:**
When running `npm run build` the following error is thrown, `npm install` and `jspm install` were run before attempting to run the build.

`$ npm run build`

```
> aurelia-ux@0.1.14 prebuild /Users/dan/Documents/spikes/aurelia-ux/ux-master
> cross-env rimraf dist

```

```
> aurelia-ux@0.1.14 build /Users/dan/Documents/spikes/aurelia-ux/ux-master
> concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"
```

```
[0] 
[0] > aurelia-ux@0.1.14 prebuild:amd /Users/dan/Documents/spikes/aurelia-ux/ux-master
[0] > cross-env rimraf dist/amd
[0] 
```
```
[1] 
[1] > aurelia-ux@0.1.14 prebuild:commonjs /Users/dan/Documents/spikes/aurelia-ux/ux-master
[1] > cross-env rimraf dist/commonjs
[1] 
```
```
[2] 
[2] > aurelia-ux@0.1.14 prebuild:es2015 /Users/dan/Documents/spikes/aurelia-ux/ux-master
[2] > cross-env rimraf dist/es2015
[2] 
```
```
[3] 
[3] > aurelia-ux@0.1.14 prebuild:system /Users/dan/Documents/spikes/aurelia-ux/ux-master
[3] > cross-env rimraf dist/system
[3] 
```
```
[0] 
[0] > aurelia-ux@0.1.14 build:amd /Users/dan/Documents/spikes/aurelia-ux/ux-master
[0] > cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd
[0] 
```
```
[1] 
[1] > aurelia-ux@0.1.14 build:commonjs /Users/dan/Documents/spikes/aurelia-ux/ux-master
[1] > cross-env tsc --project tsconfig.build.json --outDir dist/commonjs --module commonjs
[1] 
```
```
[2] 
[2] > aurelia-ux@0.1.14 build:es2015 /Users/dan/Documents/spikes/aurelia-ux/ux-master
[2] > cross-env tsc --project tsconfig.build.json --outDir dist/es2015 --module es2015
[2] 
```
```
[3] 
[3] > aurelia-ux@0.1.14 build:system /Users/dan/Documents/spikes/aurelia-ux/ux-master
[3] > cross-env tsc --project tsconfig.build.json --outDir dist/system --module system
[3] 
```
```
[0] src/effects/paper-wave.ts(342,5): error TS2531: Object is possibly 'null'.
[0] src/styles/style-controller.ts(60,5): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
[0]   Type 'null' is not assignable to type 'Node'.
[0] src/styles/style-resource.ts(34,12): error TS2322: Type 'Promise<StyleFactory>' is not assignable to type 'Promise<StyleResource>'.
[0]   Type 'StyleFactory' is not assignable to type 'StyleResource'.
[0]     Property 'styleObjectType' is private in type 'StyleFactory' but not in type 'StyleResource'.
```
```
[3] src/effects/paper-wave.ts(342,5): error TS2531: Object is possibly 'null'.
[3] src/styles/style-controller.ts(60,5): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
[3]   Type 'null' is not assignable to type 'Node'.
[3] src/styles/style-resource.ts(34,12): error TS2322: Type 'Promise<StyleFactory>' is not assignable to type 'Promise<StyleResource>'.
[3]   Type 'StyleFactory' is not assignable to type 'StyleResource'.
[3]     Property 'styleObjectType' is private in type 'StyleFactory' but not in type 'StyleResource'.
```
```
[0] 
[3] 
[0] npm
[0]  ERR! Darwin 15.5.0
[0] npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:amd"
[0] npm ERR! node v7.2.1
[0] npm ERR! npm  v3.10.10
[0] npm ERR! 
[0] code ELIFECYCLE
[0] npm ERR! aurelia-ux@0.1.14 build:amd: `cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd`
[0] npm ERR! Exit status 2
[0] npm ERR! 
[0] npm ERR! Failed at the aurelia-ux@0.1.14 build:amd script 'cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the aurelia-ux package,
[0] npm ERR! not with npm itself.
[0] npm ERR!
[0]  Tell the author that this fails on your system:
[0] npm ERR!     cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs aurelia-ux
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls aurelia-ux
[0] npm ERR! There is likely additional logging output above.
```

**Expected/desired behavior:**
Expected all tests to pass and build to succeed.

### PR DESCRIPTION
**Pull request by khuongduybui**
Did what @jdanyow suggested here: https://github.com/aurelia/ux/pull/31#issuecomment-289225303

I did not fix ALL the lint issues, so many of them, but I fixed the errors that would have broken "npm build"

### CODE REVIEW

**Comment by jdanyow** [comment]
we can get the lint errors fixed in a separate PR.

**Comment by ZHollingshead** [comment]
After pulling down this repository fresh, I ran `npm install` and tried to run `build` and `doc`

`npm run build` works as expected

`npm run doc` failed with the following output
```
> aurelia-ux@0.1.16 predoc E:\Development\Aurelia\_review\ux
> cross-env rimraf doc/api.json && rimraf dist/doc-temp && tsc --project tsconfig.build.json --outFile dist/doc-temp/aurelia-ux.js && node doc/shape-defs && copyfiles tsconfig.json dist/doc-temp

Shaped the dist/doc-temp/aurelia-ux.d.ts file.

> aurelia-ux@0.1.16 doc E:\Development\Aurelia\_review\ux
> cross-env typedoc --json doc/api.json --excludeExternals --includeDeclarations --mode modules --target ES6 --name aurelia-ux-docs dist/doc-temp/


Using TypeScript 2.2.1 from E:\Development\Aurelia\_review\ux\node_modules\typescript\lib
Error: File 'E:/lib.dom.d.ts' not found.
Error: File 'E:/lib.es2017.d.ts' not found.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "doc"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! aurelia-ux@0.1.16 doc: `cross-env typedoc --json doc/api.json --excludeExternals --includeDeclarations --mode modules --target ES6 --name aurelia-ux-docs dist/doc-temp/`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the aurelia-ux@0.1.16 doc script 'cross-env typedoc --json doc/api.json --excludeExternals --includeDeclarations --mode modules --target ES6 --name aurelia-ux-docs dist/doc-temp/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aurelia-ux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env typedoc --json doc/api.json --excludeExternals --includeDeclarations --mode modules --target ES6 --name aurelia-ux-docs dist/doc-temp/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aurelia-ux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aurelia-ux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Development\Aurelia\_review\ux\npm-debug.log
```

**Comment by jdanyow** [comment]
@ZHollingshead unfortunately this is an issue with typedoc on windows. I hit the same issue on my windows machine with their latest release and had to switch over to my unbuntu installation.

**Comment by ZHollingshead** [comment]
@jdanyow Ah, that is very unfortunate indeed. 

Other than this everything looks alright. I can fix the lint issues as soon as this is pulled in. The main issue of the build being broken is resolved.

**Comment by EisenbergEffect** [comment]
Ok, all merged in :)

**Pull request merged**
